# Generated by Django 4.2 on 2024-07-17 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=32, verbose_name='Ключ сессии')),
                ('city_name', models.CharField(max_length=100, verbose_name='Город')),
                ('search_count', models.IntegerField(default=0, verbose_name='Число запросов')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='Время последнего запроса')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
