# Generated by Django 4.2 on 2024-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citysearchhistory',
            options={'default_related_name': 'citysearchhistory', 'ordering': ('-last_searched',)},
        ),
        migrations.AlterField(
            model_name='citysearchhistory',
            name='search_count',
            field=models.IntegerField(default=1, verbose_name='Число запросов'),
        ),
        migrations.AddConstraint(
            model_name='citysearchhistory',
            constraint=models.UniqueConstraint(fields=('user', 'city_name'), name='usercity_unique'),
        ),
        migrations.AddConstraint(
            model_name='citysearchhistory',
            constraint=models.UniqueConstraint(fields=('session_key', 'city_name'), name='sessioncity_unique'),
        ),
    ]
